# Generated by Django 6.0.5 on 2026-05-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='dueño',
            new_name='dueno',
        ),
    ]
